name: unittest
on: [ push, pull_request ]

jobs:
  unittest:
    name: unittest
    strategy:
      matrix:
        zk-version: [ 3.6.2 ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25

    - name: Test code
      run: make test ZK_VERSION=${{ matrix.zk-version }}

    - name: Upload code coverage
      uses: codecov/codecov-action@v5
      with:
        files: ./profile.cov
